# This is a basic workflow to help you get started with Actions

name: modify version.txt

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/main.yml'
      - 'version.txt'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "Increment"
  Increment:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with: ${{ secrets.GITHUB_TOKEN_ACTION }}
    # Runs a multi-line using the runners shell
    - name: Read increment and output version.txt
      run: |
        VER=$(cat version.txt)
        VER=$((VER + 1))
        echo $VER >version.txt

    # Commits the updated version.txt to the repo
    - uses: stefanzweifel/git-auto-commit-action@v4.2.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN_ACTION }}
        commit_message: Version incremented by Action
    

